### ISSUE TITLE
GPG sign commits

### ISSUE THREAD

**Issue by CleanMachine1** [ryanfortner/autobuildservice#1]
How can I tell that it is you compiling the software rather than someone just using your credentials?

**Comment by chunky-milk** [comment]
> How can I tell that it is you compiling the software rather than someone just using your credentials?

Good idea to gpg sign commits. I'll work on it.

**Comment by CleanMachine1** [comment]
Takes 20 mins, follow the github documentation

**Comment by Itai-Nelken** [comment]
https://docs.github.com/en/github/authenticating-to-github/signing-commits

**Comment by ryanfortner** [comment]
It took me a long time to get around to it, but I finally created a gpg key and connected it to my account. It's here: https://raw.githubusercontent.com/ryanfortner/ryanfortner/main/ryanfortner.gpg

**Comment by CleanMachine1** [comment]
What problems did you have?

**Comment by ryanfortner** [comment]
> What problems did you have?

I didn't have any problems. I'd just completely forgotten to do it.
